name: Native Image

on:
  push:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        type: string
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build_non_win_images:
    name: 'Build Native Image ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
          - os: 'macos-latest'
            platform: 'darwin-amd64'
          - os: 'windows-latest'
            platform: 'win-amd64'
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '22'
      - run: ./gradlew plantuml-gplv2:nativeCompile

